global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Ordering.Orders.Events;
global using Ordering.Orders.Models;
global using Ordering.Orders.ValueObjects;
global using Shared.DDD;
